### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by JuGGerNaunT** [degenerated1123/ZenLib#36]
Do you have plans to implement missing data reading? Like this one
https://github.com/ataulien/ZenLib/blob/master/zenload/zCMesh.cpp#L143
some chunks are missing, some half implemented and some are just incorrect

**Comment by ataulien** [comment]
> Do you have plans to implement missing data reading?

I assume you are talking about all the formats Gothic has to offer. The plan is to implement the features as we go with REGoth. Gothics formats contain lots of data not even used by the original game.

In your particular example I can only see the two lightmap related chunks which are skipped:

https://github.com/ataulien/ZenLib/blob/e90e239f121fee2bd45ffcf38e76cb43d13ea4e4/zenload/zCMesh.cpp#L246-L252

Those contain data we haven't found a use for and thus there was no need for us to parse them. We can get all information for light mapping from data of the other chunks. 

> some half implemented and some are just incorrect

Can you elaborate on what is incorrect and what the correct behavior should be? You seem to know your way around the internal details of the file formats and I'd be happy if you could open some issues explaining where we went wrong with our implementation.

**Comment by JuGGerNaunT** [comment]
What I mean isn't completely incorrect since it work but it really confusing.

https://github.com/ataulien/ZenLib/blob/e90e239f121fee2bd45ffcf38e76cb43d13ea4e4/zenload/parserImplBinSafe.cpp#L382-L383
Like this one.  Every safe entry has a hash at its beginning but this implementation trying to read hash at the end.

https://github.com/ataulien/ZenLib/blob/e90e239f121fee2bd45ffcf38e76cb43d13ea4e4/zenload/zCMesh.cpp#L182-L184
It should be float3

https://github.com/ataulien/ZenLib/blob/e90e239f121fee2bd45ffcf38e76cb43d13ea4e4/zenload/zTypes.h#L647-L655
Even tho compiler make this struct 16 bytes length it isn't obvious and really confusing when trying to debug.

https://github.com/ataulien/ZenLib/blob/e90e239f121fee2bd45ffcf38e76cb43d13ea4e4/zenload/zCMesh.cpp#L169-L170
I don't know real purpose of this structure but its content doesn't looks like date and time.

Above is actual at least for 2.6 game version.
